-- ============================================================
-- THRUST GLOBAL LEADERBOARD
-- ============================================================

-- CREATE TABLE
CREATE TABLE IF NOT EXISTS public.thrust_leaderboard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_name TEXT NOT NULL,
    distance INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT thrust_player_name_length
        CHECK (char_length(trim(player_name)) BETWEEN 1 AND 18),

    CONSTRAINT thrust_distance_valid
        CHECK (distance >= 0)
);


-- INDEXES
CREATE INDEX IF NOT EXISTS thrust_leaderboard_distance_idx
ON public.thrust_leaderboard (distance DESC);

CREATE INDEX IF NOT EXISTS thrust_leaderboard_created_at_idx
ON public.thrust_leaderboard (created_at DESC);


-- ROW LEVEL SECURITY
ALTER TABLE public.thrust_leaderboard
ENABLE ROW LEVEL SECURITY;


-- REMOVE OLD POLICIES
DROP POLICY IF EXISTS "Anyone can read leaderboard"
ON public.thrust_leaderboard;

DROP POLICY IF EXISTS "Anyone can submit a flight"
ON public.thrust_leaderboard;

DROP POLICY IF EXISTS "Players can update their best flight"
ON public.thrust_leaderboard;


-- READ
CREATE POLICY "Anyone can read leaderboard"
ON public.thrust_leaderboard
FOR SELECT
TO anon, authenticated
USING (true);


-- INSERT
CREATE POLICY "Anyone can submit a flight"
ON public.thrust_leaderboard
FOR INSERT
TO anon, authenticated
WITH CHECK (
    char_length(trim(player_name)) BETWEEN 1 AND 18
    AND distance >= 0
);


-- UPDATE
CREATE POLICY "Players can update their best flight"
ON public.thrust_leaderboard
FOR UPDATE
TO anon, authenticated
USING (true)
WITH CHECK (
    char_length(trim(player_name)) BETWEEN 1 AND 18
    AND distance >= 0
);


-- PERMISSIONS
GRANT SELECT, INSERT, UPDATE
ON TABLE public.thrust_leaderboard
TO anon, authenticated;


-- SEQUENCE PERMISSIONS
GRANT USAGE, SELECT
ON SEQUENCE public.thrust_leaderboard_id_seq
TO anon, authenticated;


-- REALTIME
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime'
        AND schemaname = 'public'
        AND tablename = 'thrust_leaderboard'
    ) THEN

        ALTER PUBLICATION supabase_realtime
        ADD TABLE public.thrust_leaderboard;

    END IF;
END
$$;


-- VIEW CURRENT LEADERBOARD
SELECT
    id,
    player_name,
    distance,
    created_at
FROM public.thrust_leaderboard
ORDER BY distance DESC
LIMIT 100;